let greeting = "Hello, World!";
console.log(greeting);
console.log(typeof greeting);
let earth = "The earth is the only planet in the universe that can support life";
console.log(earth);
console.log(typeof earth);
let test = "100" - "10";
console.log(test);
let lady = "cheer" + "leader";
console.log(lady);
console.log(typeof lady);