let rosePrice = 8;
let lilyPrice = 10;
let tulipPrice = 2;
const flowerPrice =1300;
let roseQuantity = 70;
roseQuantity = 50;
let lilyQuantity = 50;
lilyQuantity = 20;
let tulipQuantity = 120;
let roseValue  = rosePrice * roseQuantity;
let lilyValue = lilyPrice * lilyQuantity;
let tulipValue = tulipPrice * tulipQuantity;
let totalValue = roseValue + lilyValue + tulipValue;
console.log("Rose - unit price: " + rosePrice + " , quantity: " + roseQuantity + " , value: " + roseValue);
console.log("Lily - unit price: " + lilyPrice + " , quantity: " + lilyQuantity + " , value: " + lilyValue);
console.log("Tulip - unit price: " + tulipPrice + " , quantity: " + tulipQuantity + " , value: " + tulipValue);
console.log("Total:" , totalValue );